language: generic
sudo: required
services:
    - docker
before_install:
    - docker build -t seand52/invoices-client -f ./client/Dockerfile.dev ./client
    - docker build -t seand52/invoices-api -f ./api/Dockerfile.dev ./api
script:
    - docker run -e CI=true seand52/invoices-client yarn test
    - docker run -e CI=true seand52/invoices-api yarn test
after_success:
    - docker build -t seand52/invoices-client ./client
    - docker build -t seand52/invoices-api ./api
    - docker build -t seand52/invoices-nginx ./nginx

    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

    - docker push seand52/invoices-client
    - docker push seand52/invoices-api
    - docker push seand52/invoices-nginx
deploy:
    provider: elasticbeanstalk
    region: eu-west-1
    app: invoices-app
    env: InvoicesApp-env
    bucket_name: elasticbeanstalk-eu-west-1-294472240262
    bucket_path: invoices-app
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY