version: '3'

services: 
    client:
        stdin_open: true
        container_name: 'invoices-client'
        build:
            context: ./client
            dockerfile: Dockerfile.dev
        volumes:
            - /app/node_modules
            - ./client:/app
    api:
        container_name: 'invoices-api'
        build:
            context: ./api
            dockerfile: Dockerfile.dev
        volumes:
            - /app/node_modules
            - ./api:/app
        environment: 
            - MYSQL_HOST=db
            - MYSQL_ROOT_PASSWORD=mysqlpassword
            - MYSQL_DATABASE=invoices
            - MYSQL_USER=user
            - MYSQL_PASSWORD=mysqlpassword
            - MYSQL_PORT=3306
            - API_URL=http://localhost:3000/api
            - JWT_SECRET=masecret
        depends_on:
            - db
    db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment: 
            MYSQL_ROOT_PASSWORD: mysqlpassword
            MYSQL_PASSWORD: mysqlpassword
            MYSQL_HOST: db
            MYSQL_DATABASE: invoices
            MYSQL_USER: user
            MYSQL_PASSWORD: mysqlpassword
            MYSQL_PORT: 3306
        
        
